# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
- pip install coveralls
- python setup.py install
#pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
# script: tox

before_install:
- pip install coverage
- pip install matplotlib
- sudo apt-get install -qq python-numpy python-scipy python-matplotlib

script:
- coverage run --source=Langevin setup.py test
- coverage report -m

after_success: coveralls
language: python

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: wfunkenbusch
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: wfunkenbusch/1D_Langevin
    python: 3.6
